# Configuration for the Azure AD application used to authenticate (see setup instructions in README)
# (Required)
azureClientId: ""
azureClientSecret: ""
azureTenantId: ""

# Format for the webhook request
# Supported values are "plain" (default) or "slack"
webhookFormat: "plain"

# URL of the webhook to send notifications to
# Will send the notification in the POST body as text/plain
# (Required)
webhookUrl: ""

# Optional key to authenticate with the webhook URL
# If present, will be passed as value for the "Authorization" header in requests to the webhook
webhookKey: ""

# Path to TLS certificate and key
# If empty, it will load a certificate from "tls-cert.pem" and a key from "tls-key.pem" in the same folder as the config file
tlsCert: ""
tlsKey: ""

# Port to listen to
# Default: 8080
port: 8080

# Address to listen on
# Default: "0.0.0.0" to listen on every interface
bind: "0.0.0.0"

# Comma-separated list of IPs (and IP ranges in CIDR notation) that are allowed to invoke the /wrap, /unwrap and /result methods
# If empty, all requests are allowed
# This doesn't apply to the endpoints used by admins to confirm requests
allowedIps: ""

# Comma-separated lists of origins for CORS
# If empty or unset, will the same as baseUrl
# To allow any origin, set value to "*"
#origins: "https://url1,https://url2"

# Base URL where the application is deployed, used for authentication callbacks and in notifications
# This URL must be routable by clients (administrators), but doesn't need to be public
# Default: "https://localhost:8080"
baseUrl: "https://localhost:8080"
