FROM gcr.io/distroless/static-debian13:nonroot@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6
# TARGETARCH is set automatically when using BuildKit
ARG TARGETARCH
# Default path for the trust store
ENV TRUST_STORE_PATH=/data/trust.json
COPY .bin/linux-${TARGETARCH}/revaulter-cli /bin
ENTRYPOINT ["/bin/revaulter-cli"]
