// Code generated by go generate; DO NOT EDIT.
// Regenerate with: go generate ./pkg/db/backup/
// (Requires TEST_DATABASE_DSN to be set for accurate Postgres type information)

package backup

// backupTables lists the persistent tables included in a backup, in FK-safe order (parents before children so that FK constraints are satisfied on restore)
//
// Ephemeral tables (v2_auth_challenges, v2_auth_challenge_payloads) and the metadata table are excluded from backups
var backupTables = []tableSpec{
	{
		name: "v2_users",
		columns: []columnSpec{
			{name: "id", kind: colKindText},
			{name: "display_name", kind: colKindText},
			{name: "status", kind: colKindText},
			{name: "webauthn_user_id", kind: colKindText},
			{name: "request_key", kind: colKindText},
			{name: "request_enc_ecdh_pubkey", kind: colKindText},
			{name: "request_enc_mlkem_pubkey", kind: colKindText},
			{name: "anchor_es384_public_key", kind: colKindText},
			{name: "anchor_mldsa87_public_key", kind: colKindText},
			{name: "pubkey_bundle_signature_es384", kind: colKindText},
			{name: "pubkey_bundle_signature_mldsa87", kind: colKindText},
			{name: "wrapped_key_epoch", kind: colKindText},
			{name: "allowed_ips", kind: colKindText},
			{name: "ready", kind: colKindBool},
			{name: "created_at", kind: colKindText},
			{name: "updated_at", kind: colKindText},
		},
	},
	{
		name: "v2_user_credentials",
		columns: []columnSpec{
			{name: "id", kind: colKindText},
			{name: "user_id", kind: colKindText},
			{name: "credential_id", kind: colKindText},
			{name: "display_name", kind: colKindText},
			{name: "public_key", kind: colKindText},
			{name: "sign_count", kind: colKindText},
			{name: "wrapped_primary_key", kind: colKindText},
			{name: "wrapped_anchor_key", kind: colKindText},
			{name: "attestation_payload", kind: colKindText},
			{name: "attestation_signature_es384", kind: colKindText},
			{name: "attestation_signature_mldsa87", kind: colKindText},
			{name: "wrapped_key_epoch", kind: colKindText},
			{name: "created_at", kind: colKindText},
			{name: "last_used_at", kind: colKindText},
		},
	},
	{
		name: "v2_requests",
		columns: []columnSpec{
			{name: "state", kind: colKindText},
			{name: "status", kind: colKindText},
			{name: "operation", kind: colKindText},
			{name: "user_id", kind: colKindText},
			{name: "key_label", kind: colKindText},
			{name: "algorithm", kind: colKindText},
			{name: "requestor_ip", kind: colKindText},
			{name: "note", kind: colKindText},
			{name: "created_at", kind: colKindText},
			{name: "expires_at", kind: colKindText},
			{name: "updated_at", kind: colKindText},
			{name: "encrypted_request", kind: colKindText},
			{name: "encrypted_result", kind: colKindText},
		},
	},
	{
		name: "v2_published_signing_keys",
		columns: []columnSpec{
			{name: "id", kind: colKindText},
			{name: "user_id", kind: colKindText},
			{name: "algorithm", kind: colKindText},
			{name: "key_label", kind: colKindText},
			{name: "jwk", kind: colKindText},
			{name: "pem", kind: colKindText},
			{name: "published", kind: colKindBool},
			{name: "publication_payload", kind: colKindText},
			{name: "publication_signature_es384", kind: colKindText},
			{name: "publication_signature_mldsa87", kind: colKindText},
			{name: "created_at", kind: colKindText},
			{name: "updated_at", kind: colKindText},
		},
	},
	{
		name: "v2_audit_events",
		columns: []columnSpec{
			{name: "id", kind: colKindUUID},
			{name: "created_at", kind: colKindText},
			{name: "event_type", kind: colKindText},
			{name: "outcome", kind: colKindText},
			{name: "auth_method", kind: colKindText},
			{name: "actor_user_id", kind: colKindText},
			{name: "target_user_id", kind: colKindText},
			{name: "signing_key_id", kind: colKindText},
			{name: "credential_id", kind: colKindText},
			{name: "request_state", kind: colKindText},
			{name: "http_request_id", kind: colKindText},
			{name: "client_ip", kind: colKindText},
			{name: "user_agent", kind: colKindText},
			{name: "metadata", kind: colKindJSONB},
		},
	},
}
